services:
  library:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
    depends_on:
      - redis
      - library
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    command: >
      sh -c "celery -A core worker --loglevel=info --pool=solo"

  celery-beat:
    build:
      context: .
    depends_on:
      - redis
      - library
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    command: >
      sh -c "python manage.py migrate django_celery_beat && celery -A core beat --loglevel=info"

volumes:
  my_db:
