name: Test

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.12.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.8"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run Ruff
        run: poetry run ruff check

      - name: Run Tests
        timeout-minutes: 5
        run: poetry run python manage.py test