name: Test

on:
  pull_request:
    branches:
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.12.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.8"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run Ruff
        run: poetry run ruff check --output-format=github .

      - name: make
        run: poetry run ruff check --output-format=github .

      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
        timeout-minutes: 5
        run: poetry run python manage.py test
